<?php
/**
 * Danjulf_TinyDomesticator
 *
 * Copyright (C) 2014 Daniel Bergstrom (danjulf@gmail.com)
 *
 * This file is part of Danjulf_TinyDomesticator.
 *
 * Danjulf_TinyDomesticator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Danjulf_TinyDomesticator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Danjulf_TinyDomesticator. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category  Danjulf
 * @package   Danjulf_TinyDomesticator
 * @author    Daniel Bergstrom <danjulf@gmail.com>
 * @copyright 2014 Daniel Bergstrom (danjulf@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 */
?>
<?php if ($this->isEnabled()): ?>
<?php $settings = $this->getConfigSettings(); ?>
<script type="text/javascript">
(function(exports){
    if(exports.tinyMceWysiwygSetup) {
        tinyMceWysiwygSetup.prototype.originalGetSettings = tinyMceWysiwygSetup.prototype.getSettings;
        tinyMceWysiwygSetup.prototype.getSettings = function(mode) {
            var settings = this.originalGetSettings(mode);

            <?php foreach ($settings as $setting => $value): ?>
                <?php if (!empty($setting)): ?>
                settings.<?php echo $setting; ?> = <?php echo $value; ?>;
                <?php endif; ?>
            <?php endforeach; ?>

            return settings;
        }
    }
})(window);
</script>
<?php endif; ?>

